'use client';

import { useState } from 'react';
import { useSimulationStore } from '@/store/useSimulationStore';
import type { SimRecord } from '@/store/useSimulationStore';
import Link from 'next/link';
import { FileText, Download, Calendar, TrendingUp, TrendingDown, Clock, Share2, FlaskConical } from 'lucide-react';

export default function Reports() {
  const { policyLabHistory, clearPolicyLabHistory } = useSimulationStore();
  const [selectedSimulation, setSelectedSimulation] = useState<SimRecord | null>(null);

  const formatDate = (dateStr: string) =>
    new Date(dateStr).toLocaleDateString('en-US', {
      month: 'short', day: 'numeric', year: 'numeric', hour: '2-digit', minute: '2-digit',
    });

  const exportToCSV = (data: SimRecord[]) => {
    const headers = ['ID', 'Timestamp', 'Sensitive Feature', 'Years Simulated', 'Threshold Adjustment', 'Demographic Parity Ratio', 'Demographic Parity Diff', 'Approval Rate', 'Status'];
    const rows = data.map(sim => [
      sim.id, sim.timestamp, sim.sensitive_feature, sim.years_simulated, sim.threshold_adjustment,
      sim.metrics.demographic_parity_ratio, sim.metrics.demographic_parity_difference,
      sim.metrics.approval_rate_overall,
      sim.metrics.demographic_parity_ratio >= 0.8 ? 'Compliant' : 'Non-Compliant',
    ]);
    const csvContent = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
    const link = document.createElement('a');
    link.href = URL.createObjectURL(new Blob([csvContent], { type: 'text/csv;charset=utf-8;' }));
    link.download = `decisiontwin_report_${new Date().toISOString().split('T')[0]}.csv`;
    link.click();
  };

  const exportSingleReport = (sim: SimRecord) => {
    const content = `DECISION TWIN - BIAS AUDIT REPORT
Generated: ${new Date().toISOString()}
=====================================

SIMULATION SUMMARY
------------------
Sensitive Feature:          ${sim.sensitive_feature}
Years Simulated:            ${sim.years_simulated}
Threshold Adjustment:       ${sim.threshold_adjustment}

FAIRNESS METRICS
----------------
Demographic Parity Ratio:   ${sim.metrics.demographic_parity_ratio}
Demographic Parity Diff:    ${sim.metrics.demographic_parity_difference}
Overall Approval Rate:      ${(sim.metrics.approval_rate_overall * 100).toFixed(1)}%

COMPLIANCE STATUS
-----------------
${sim.metrics.demographic_parity_ratio >= 0.8
  ? '✓ PASS - Bias metrics within acceptable legal thresholds'
  : '✗ FAIL - Bias metrics exceed legal thresholds (80% Rule violation)'}

${sim.report ? `EXECUTIVE SUMMARY\n------------------\n${sim.report}` : ''}

=====================================
This report was generated by DecisionTwin AI Ethics Platform`;

    const link = document.createElement('a');
    link.href = URL.createObjectURL(new Blob([content], { type: 'text/plain' }));
    link.download = `bias_audit_${sim.id}.txt`;
    link.click();
  };

  const avgRatio = policyLabHistory.length > 0
    ? (policyLabHistory.reduce((acc, s) => acc + s.metrics.demographic_parity_ratio, 0) / policyLabHistory.length).toFixed(3)
    : '—';
  const passRate = policyLabHistory.length > 0
    ? Math.round((policyLabHistory.filter(s => s.metrics.demographic_parity_ratio >= 0.8).length / policyLabHistory.length) * 100)
    : 0;

  return (
    <main className="min-h-screen p-8 max-w-7xl mx-auto space-y-8 animate-fade-in-up">
      <header className="flex justify-between items-end border-b border-slate-100 pb-6">
        <div>
          <h1 className="text-3xl font-extrabold text-slate-800 mb-2 tracking-tight">Reports</h1>
          <p className="text-slate-400 text-sm">Historical simulations, exports, and compliance documentation</p>
        </div>
        <div className="flex gap-4">
          <button
            onClick={() => exportToCSV(policyLabHistory)}
            disabled={policyLabHistory.length === 0}
            className="flex items-center gap-2 px-4 py-2.5 border border-slate-200 hover:border-slate-300 text-slate-600 bg-white rounded-xl transition-all font-semibold shadow-sm hover:shadow disabled:opacity-50"
          >
            <Download className="w-4 h-4" />
            Export CSV
          </button>
        </div>
      </header>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <div className="glass-card p-6">
          <div className="flex items-center gap-3 mb-2">
            <Clock className="w-5 h-5" style={{ color: '#F97316' }} />
            <span className="text-sm text-slate-400">Total Simulations</span>
          </div>
          <span className="text-3xl font-bold text-slate-800">{policyLabHistory.length}</span>
        </div>
        <div className="glass-card p-6">
          <div className="flex items-center gap-3 mb-2">
            <TrendingDown className="w-5 h-5 text-rose-500" />
            <span className="text-sm text-slate-400">Avg Disparity Ratio</span>
          </div>
          <span className="text-3xl font-bold text-slate-800">
            {avgRatio}
          </span>
        </div>
        <div className="glass-card p-6">
          <div className="flex items-center gap-3 mb-2">
            <TrendingUp className="w-5 h-5 text-emerald-600" />
            <span className="text-sm text-slate-400">Pass Rate (80% Rule)</span>
          </div>
          <span className="text-3xl font-bold text-emerald-600">
            {passRate}%
          </span>
        </div>
        <div className="glass-card p-6">
          <div className="flex items-center gap-3 mb-2">
            <Calendar className="w-5 h-5 text-amber-600" />
            <span className="text-sm text-slate-400">Last Simulation</span>
          </div>
          <span className="text-lg font-bold text-slate-800">
            {policyLabHistory.length > 0 ? formatDate(policyLabHistory[0].timestamp).split(',')[0] : '—'}
          </span>
        </div>
      </div>

      {/* Historical Simulations Table */}
      <div className="glass-card p-6">
        <h2 className="text-xl font-bold text-slate-800 mb-6">Historical Simulations</h2>
        
        {policyLabHistory.length === 0 ? (
          <div className="py-16 flex flex-col items-center justify-center gap-4 text-center">
            <FlaskConical className="w-14 h-14 text-slate-300" />
            <div>
              <p className="text-slate-500 font-semibold text-sm">No simulations recorded yet.</p>
              <p className="text-slate-400 text-xs mt-1 leading-relaxed">
                Run a simulation in{' '}
                <Link href="/policy-lab" className="text-orange-500 font-semibold hover:underline">Policy Lab</Link>
                {' '}and the results will appear here automatically.
              </p>
            </div>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b border-slate-100 text-left">
                  <th className="py-3 px-4 text-slate-400 font-semibold text-xs uppercase tracking-wider">Date</th>
                  <th className="py-3 px-4 text-slate-400 font-semibold text-xs uppercase tracking-wider">Sensitive Feature</th>
                  <th className="text-right py-3 px-4 text-slate-400 font-semibold text-xs uppercase tracking-wider">Years</th>
                  <th className="text-right py-3 px-4 text-slate-400 font-semibold text-xs uppercase tracking-wider">Parity Ratio</th>
                  <th className="text-right py-3 px-4 text-slate-400 font-semibold text-xs uppercase tracking-wider">Approval Rate</th>
                  <th className="text-center py-3 px-4 text-slate-400 font-semibold text-xs uppercase tracking-wider">Status</th>
                  <th className="text-center py-3 px-4 text-slate-400 font-semibold text-xs uppercase tracking-wider">Actions</th>
                </tr>
              </thead>
              <tbody>
                {policyLabHistory.map((sim, idx) => {
                  const prevSim = policyLabHistory[idx + 1];
                  const trend = prevSim
                    ? sim.metrics.demographic_parity_ratio - prevSim.metrics.demographic_parity_ratio
                    : null;
                  const passesThreshold = sim.metrics.demographic_parity_ratio >= 0.8;

                  return (
                    <tr
                      key={sim.id}
                      className={`border-b border-slate-100/50 hover:bg-slate-50/30 cursor-pointer ${selectedSimulation?.id === sim.id ? 'bg-orange-50/20' : ''}`}
                      onClick={() => setSelectedSimulation(sim)}
                    >
                      <td className="py-3.5 px-4 text-slate-500 text-sm">
                        <div className="flex items-center gap-2">
                          <Calendar className="w-4 h-4 text-slate-400" />
                          {formatDate(sim.timestamp)}
                        </div>
                      </td>
                      <td className="py-3.5 px-4 text-slate-700 capitalize font-medium text-sm">{sim.sensitive_feature.replace('_', ' ')}</td>
                      <td className="text-right py-3.5 px-4 font-mono text-slate-600 text-sm">{sim.years_simulated}</td>
                      <td className="text-right py-3.5 px-4">
                        <div className="flex items-center justify-end gap-2 text-sm font-semibold">
                          <span className={`${passesThreshold ? 'text-emerald-600' : 'text-rose-600'}`}>
                            {sim.metrics.demographic_parity_ratio.toFixed(4)}
                          </span>
                          {trend !== null && (
                            trend > 0
                              ? <TrendingUp className="w-4 h-4 text-emerald-500" />
                              : <TrendingDown className="w-4 h-4 text-rose-500" />
                          )}
                        </div>
                      </td>
                      <td className="text-right py-3.5 px-4 font-mono text-blue-900 font-semibold text-sm">
                        {(sim.metrics.approval_rate_overall * 100).toFixed(1)}%
                      </td>
                      <td className="text-center py-3.5 px-4">
                        <span className={`px-2 py-1 rounded-lg text-xs font-semibold ${
                          passesThreshold
                            ? 'bg-emerald-50 text-emerald-700'
                            : 'bg-rose-50 text-rose-700'
                        }`}>
                          {passesThreshold ? 'Compliant' : 'Non-Compliant'}
                        </span>
                      </td>
                      <td className="text-center py-3.5 px-4">
                        <button
                          onClick={(e) => { e.stopPropagation(); exportSingleReport(sim); }}
                          className="p-1.5 hover:bg-slate-100 rounded-lg transition-colors inline-flex items-center justify-center"
                          title="Export report"
                        >
                          <Download className="w-4 h-4 text-slate-400" />
                        </button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Selected Simulation Detail */}
      {selectedSimulation && (
        <div className="glass-card p-6 space-y-6">
          <div className="flex justify-between items-start">
            <div>
              <h2 className="text-xl font-bold text-slate-800 mb-1">Simulation Detail</h2>
              <p className="text-slate-400 text-xs">{formatDate(selectedSimulation.timestamp)}</p>
            </div>
            <button
              onClick={() => setSelectedSimulation(null)}
              className="text-slate-400 hover:text-slate-600 font-semibold text-lg"
            >
              ×
            </button>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
            <div className="p-4 bg-[#F8FAFC] rounded-2xl">
              <div className="text-xs text-slate-400 mb-1 font-semibold">Parity Ratio</div>
              <div className={`text-2xl font-bold ${selectedSimulation.metrics.demographic_parity_ratio >= 0.8 ? 'text-emerald-600' : 'text-rose-600'}`}>
                {selectedSimulation.metrics.demographic_parity_ratio.toFixed(4)}
              </div>
            </div>
            <div className="p-4 bg-[#F8FAFC] rounded-2xl">
              <div className="text-xs text-slate-400 mb-1 font-semibold">Parity Diff</div>
              <div className="text-2xl font-bold text-amber-600">
                {selectedSimulation.metrics.demographic_parity_difference.toFixed(4)}
              </div>
            </div>
            <div className="p-4 bg-[#F8FAFC] rounded-2xl">
              <div className="text-xs text-slate-400 mb-1 font-semibold">Approval Rate</div>
              <div className="text-2xl font-bold text-blue-900">
                {(selectedSimulation.metrics.approval_rate_overall * 100).toFixed(1)}%
              </div>
            </div>
            <div className="p-4 bg-[#F8FAFC] rounded-2xl">
              <div className="text-xs text-slate-400 mb-1 font-semibold">Years Simulated</div>
              <div className="text-2xl font-bold text-slate-800">
                {selectedSimulation.years_simulated}
              </div>
            </div>
          </div>

          {selectedSimulation.report && (
            <div className="p-6 bg-blue-50/50 border border-blue-100 rounded-2xl">
              <h3 className="text-base font-bold text-blue-900 mb-3">AI-Generated Report</h3>
              <p className="text-slate-600 text-sm leading-relaxed whitespace-pre-wrap">{selectedSimulation.report}</p>
            </div>
          )}

          <div className="flex gap-4">
            <button
              onClick={() => exportToCSV([selectedSimulation])}
              className="flex items-center gap-2 px-4 py-2 border border-slate-200 hover:border-slate-300 text-slate-600 bg-white rounded-xl font-semibold text-xs shadow-sm hover:shadow"
            >
              <Download className="w-4 h-4" />
              Export This Simulation
            </button>
            <button 
              onClick={() => exportSingleReport(selectedSimulation)}
              className="flex items-center gap-2 px-4 py-2 border border-slate-200 hover:border-slate-300 text-slate-600 bg-white rounded-xl font-semibold text-xs shadow-sm hover:shadow"
            >
              <FileText className="w-4 h-4" />
              Download Audit File
            </button>
          </div>
        </div>
      )}
    </main>
  );
}
